#Constantes Generales
REESCALADO = 3

#Constantes de Pantalla
SCREEN_WIDTH = 160 * REESCALADO
SCREEN_HEIGTH = 210 * REESCALADO
SCREEN_RES = [SCREEN_WIDTH, SCREEN_HEIGTH]

#Constantes del Jugador
PLAYER_LASER_CD = 800
PLAYER_SPEED = 3 * REESCALADO
PLAYER_LASER_SPEED = -5 * REESCALADO
PLAYER_START_POS = [SCREEN_WIDTH / 2, SCREEN_HEIGTH - 2 * REESCALADO]
PLAYER_WIDTH = 15 * REESCALADO
PLAYER_HEIGTH = 12 * REESCALADO

#Constantes de los Aliens
ALIEN_LASER_CD = 100

#Constantes del Laser
LASER_WIDTH = 2 * REESCALADO
LASER_HEIGTH = 10 * REESCALADO