#Constantes Generales
REESCALADO = 4
SPEED_INCREMENT = 0.0005

#Constantes de Pantalla
SCREEN_WIDTH = 160 * REESCALADO
SCREEN_HEIGTH = 210 * REESCALADO
SCREEN_RES = [SCREEN_WIDTH, SCREEN_HEIGTH]

#Constantes del Jugador
PLAYER_LASER_CD = 800
PLAYER_SPEED = 2 * REESCALADO
PLAYER_START_POS = [SCREEN_WIDTH / 2, SCREEN_HEIGTH - 2 * REESCALADO]
PLAYER_WIDTH = 15 * REESCALADO
PLAYER_HEIGTH = 8 * REESCALADO

#Constantes de los Aliens
ALIEN_IMAGE_SIZE = [10 * REESCALADO, 8 * REESCALADO]
ALIEN_LASER_CD = 100
ALIEN_NUMBER_COLUMNS = 8
ALIEN_NUMBER_ROWS = 6
ALIEN_START_POS = [20 * REESCALADO, 40 * REESCALADO]
ALIEN_X_SPACING = 5 * REESCALADO + ALIEN_IMAGE_SIZE[0]
ALIEN_Y_SPACING = 5 * REESCALADO + ALIEN_IMAGE_SIZE[1]
ALIEN_X_SPEED = 0.3 * REESCALADO
ALIEN_Y_SPEED = 1 * REESCALADO
MIN_LASER_CD = 40
MAX_LASER_CD = 80

#Constantes de la nave nodriza
MOTHERSHIP_SPEED = 0.8 * REESCALADO
MOTHERSHIP_MIN_CD = 500
MOTHERSHIP_MAX_CD = 2000
MOTHERSHIP_IMAGE_SIZE = [15 * REESCALADO, 10 * REESCALADO]
MOTHERSHIP_Y = ALIEN_START_POS[1] - ALIEN_Y_SPACING

#Constantes del Laser
LASER_WIDTH = 1 * REESCALADO
LASER_HEIGTH = 6 * REESCALADO
LASER_SPEED = 3 * REESCALADO