from enum import Enum

# AI training
TRAINING_MODE = False


# Game status constants
class Game_status(Enum):
    PLAYABLE_SCREEN = 0
    FINAL_SCREEN = 1
    GAME_OVER = 2
    UNINITIALIZED = 3
    INITIALIZED = 4


# Main Screen
MENU_SCREEN_SIZE = [480, 630]
MENU_SIZE = [300, 400]

# Game
SPEED_INCREMENT = 1.03
FPS = 60
FPS_MULTIPLIER = 60 / FPS

# Screen
SCREEN_WIDTH = 480
SCREEN_HEIGHT = 630
SCREEN_RES = [SCREEN_WIDTH, SCREEN_HEIGHT]
SCORE_FONT_SIZE = 30
LEADERBOARD_FONT_SIZE = 30
LEADERBOARD_TITLE_FONT_SIZE = 45
LEADERBOARD_TITLE_CENTER_POS = [SCREEN_WIDTH / 2, SCREEN_HEIGHT / 10]
GAME_OVER_FONT_SIZE = 45
GAME_OVER_CENTER_POS = [SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2]
FINAL_SCORE_CENTER_POS = [SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2 + 60]
LEADERBOARD_CENTER_POS = [SCREEN_WIDTH / 2, SCREEN_HEIGHT / 3]
RETURN_FONT_SIZE = GAME_OVER_FONT_SIZE // 2
RETURN_CENTER_POS = [FINAL_SCORE_CENTER_POS[0], FINAL_SCORE_CENTER_POS[1] + GAME_OVER_FONT_SIZE]

TV_LINE_HEIGHT = 3
NUM_TV_LINES = SCREEN_HEIGHT // TV_LINE_HEIGHT

# Planet
PLANET_WIDTH = SCREEN_WIDTH
PLANET_HEIGHT = SCREEN_HEIGHT // 10
PLANET_X = 0
PLANET_Y = SCREEN_HEIGHT - PLANET_HEIGHT

# Player
PLAYER_LASER_CD = 40
PLAYER_SPEED = 6
PLAYER_START_POS = [SCREEN_WIDTH / 2, SCREEN_HEIGHT - 3 - PLANET_HEIGHT]
PLAYER_DIMENSIONS = [45, 24]

# Aliens
ALIEN_LASER_CD = 90
ALIEN_NUMBER_COLUMNS = 8
ALIEN_NUMBER_ROWS = 6
MIN_LASER_CD = 40
MAX_LASER_CD = 80
ALIEN_IMAGE_SIZE = [27, 20]
ALIEN_START_POS = [60, 155]
ALIEN_X_SPACING = 18 + ALIEN_IMAGE_SIZE[0]
ALIEN_Y_SPACING = 6 + ALIEN_IMAGE_SIZE[1]
ALIEN_X_SPEED = 0.6
ALIEN_Y_SPEED = 2
ALIEN_MAX_Y = SCREEN_HEIGHT - SCREEN_HEIGHT // 10

# Mothership
MOTHERSHIP_MIN_CD = 500
MOTHERSHIP_MAX_CD = 2000

# Mothership
MOTHERSHIP_SPEED = 2.4
MOTHERSHIP_IMAGE_SIZE = [45, 35]
MOTHERSHIP_Y = ALIEN_START_POS[1] - ALIEN_Y_SPACING

# Laser
LASER_DIMENSIONS = [3, 18]
LASER_SPEED = 10

# Lives
NUM_LIVES = 3
LIVES_X_START = SCREEN_WIDTH - 45
LIVES_Y = 15
LIVES_SPACE = 9
LIVES_IMG_DIMENSIONS = PLAYER_DIMENSIONS

# Obstacle
OBSTACLE_SHAPE = [
    '  xxxx',
    ' xxxxxx',
    'xxxxxxxx',
    'xx    xx',
    'x      x',
]

BLOCK_SIZE = 6
BLOCK_COLOR = (241, 79, 79)
OBSTACLE_X_START = 78
OBSTACLE_Y_START = PLAYER_START_POS[1] - 90
NUM_OBSTACLES = 3
OBSTACLE_SPACE = 90
OBSTACLE_LENGTH = len(OBSTACLE_SHAPE[3]) * BLOCK_SIZE
